name: 'Multi-eGO test'

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-reset-${{ github.sha }}
        restore-keys: ccache-reset-
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
      # source: https://autobencoder.com/2020-08-24-conda-actions/
    - name: Install dependencies with conda
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install pytest
      run: |
        conda install pytest
    - name: Run tests
      # run: .venv/bin/pytest
      run: |
        pytest run_tests.py
